# Christopher Iliffe Sprague
# cisprague@ac.jaxa.jp

# Optimisation problem parametres for point to point (PTP) spacecraft
# trajectory optimisation using neural network controller.
# Z = [(t0), tf, mf, {Wᵢ, bᵢ} ∀ i ∈ {0,…,N-1}]
---

# gravitational influences, i.e. NAIF ID or name
bodies: [Earth, Moon, Sun]

# spacecraft parametres
isp:    243   # specific impulse [s]
mass:   8165    # wet mass         [kg]
thrust: 68.17e3 # max thrust       [N]
mf:     500    # final mass       [kg]

# inner shape of neural network
net: [10, 10]

# epoch times [s]
t0:   "11/12/2004 00:00:00.000"
t0lb: "11/12/2004 00:00:00.000"
t0ub: "11/12/2004 00:00:00.000"

# terminal times [s]
tf:   "8/2/2020 00:00:00.000"
tflb: "11/12/2004 00:00:00.000"
tfub: "8/2/2040 00:00:00.000"

# NAIF ID or name of boundary points (callable by time)
origin: 1
target: 392
